export const fakeData = [
  {
    id: "9s41rp",
    firstName: "Kelvin",
    lastName: "Langosh",
    email: "Jerod14@hotmail.com",
    state: "Ohio",
  },
  {
    id: "08m6rx",
    firstName: "Molly",
    lastName: "Purdy",
    email: "Hugh.Dach79@hotmail.com",
    state: "Rhode Island",
  },
  {
    id: "5ymtrc",
    firstName: "Henry",
    lastName: "Lynch",
    email: "Camden.Macejkovic@yahoo.com",
    state: "California",
  },
  {
    id: "ek5b97",
    firstName: "Glenda",
    lastName: "Douglas",
    email: "Eric0@yahoo.com",
    state: "Montana",
  },
  {
    id: "xxtydd",
    firstName: "Leone",
    lastName: "Williamson",
    email: "Ericka_Mueller52@yahoo.com",
    state: "Colorado",
  },
  {
    id: "wzxj9m",
    firstName: "Mckenna",
    lastName: "Friesen",
    email: "Veda_Feeney@yahoo.com",
    state: "New York",
  },
  {
    id: "21dwtz",
    firstName: "Wyman",
    lastName: "Jast",
    email: "Melvin.Pacocha@yahoo.com",
    state: "Montana",
  },
  {
    id: "o8oe4k",
    firstName: "Janick",
    lastName: "Willms",
    email: "Delfina12@gmail.com",
    state: "Nebraska",
  },
];

export const usStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
];
export const videoData = [
  {
    id: 1,
    status: "active",
    title: "Interstellar",
    duration: 10140000,
    description:
      "A sci-fi epic about space exploration directed by Christopher Nolan.",
    channelId: 1,
    typeId: 2,
    categoryId: 2,
    videoUrl: "https://youtu.be/zSWdZVtXT7E",
  },
  {
    id: 2,
    status: "active",
    title: "Inception",
    duration: 8880000,
    description:
      "A mind-bending thriller about dreams within dreams directed by Christopher Nolan.",
    channelId: 1,
    typeId: 2,
    categoryId: 2,
    videoUrl: "https://youtu.be/YoHD9XEInc0",
  },
  {
    id: 3,
    status: "inactive",
    title: "The Matrix",
    duration: 8160000,
    description:
      "A hacker learns about the true nature of reality and his role in a war against its controllers.",
    channelId: 2,
    typeId: 3,
    categoryId: 1,
    videoUrl: "https://youtu.be/vKQi3bBA1y8",
  },
  {
    id: 4,
    status: "active",
    title: "Blade Runner 2049",
    duration: 9800000,
    description:
      "A sequel to Blade Runner, exploring a dystopian future with androids.",
    channelId: 3,
    typeId: 2,
    categoryId: 3,
    videoUrl: "https://youtu.be/gCcx85zbxz4",
  },
  {
    id: 5,
    status: "inactive",
    title: "The Dark Knight",
    duration: 9120000,
    description:
      "Batman faces off against the Joker in this acclaimed superhero film.",
    channelId: 1,
    typeId: 1,
    categoryId: 4,
    videoUrl: "https://youtu.be/EXeTwQWrcwY",
  },
  {
    id: 6,
    status: "active",
    title: "Avatar",
    duration: 9720000,
    description:
      "A paraplegic Marine dispatched to Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    channelId: 2,
    typeId: 2,
    categoryId: 2,
    videoUrl: "https://youtu.be/5PSNL1qE6VY",
  },
  {
    id: 7,
    status: "inactive",
    title: "Titanic",
    duration: 11700000,
    description:
      "A love story set against the ill-fated maiden voyage of the R.M.S. Titanic.",
    channelId: 3,
    typeId: 1,
    categoryId: 4,
    videoUrl: "https://youtu.be/kVrqfYjkTdQ",
  },
  {
    id: 8,
    status: "active",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    duration: 12840000,
    description:
      "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.",
    channelId: 1,
    typeId: 3,
    categoryId: 1,
    videoUrl: "https://youtu.be/V75dMMIW2B4",
  },
  {
    id: 9,
    status: "active",
    title: "The Shawshank Redemption",
    duration: 8520000,
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    channelId: 2,
    typeId: 1,
    categoryId: 4,
    videoUrl: "https://youtu.be/6hB3S9bIaco",
  },
  {
    id: 10,
    status: "inactive",
    title: "Forrest Gump",
    duration: 8520000,
    description:
      "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    channelId: 3,
    typeId: 1,
    categoryId: 4,
    videoUrl: "https://youtu.be/bLvqoHBptjg",
  },
];
